### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by ld793** [INFO-526-SU24/final-project-lestrada#1]
The following is the peer review of the project proposal by Data Duo. The team members that participated in this review are 

- Luis Diaz - @ld793 
- Jeevana Sai Devi Sathwika Karri @SathwikaKarri 

- Describe the goal of the project.
Analyze a database about coffee testing and they want to find out which age group spends the most money on coffee per month and the preferred kinds of coffee among age groups. Their analysis aims to uncover patterns and insights into the types of coffee people enjoy, their spending habits on coffee

- Describe the data used or collected.
The data contains 57 variables, categorical and numerical. It contains a total of 4040 observations. 

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Create either a heat map-like plot with count as a gradient or stacked bar charts. 

- Is there anything that is unclear from the proposal?
The following could be more clear: exact age ranges for each group and coffee types in the variable. 

- Provide constructive feedback on how the team might be able to improve their project.
For Q2 there are only two variables involved in the question being asked (favorite, age). We recommend to include an additional variable to meet the requirement. 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are interested in seeing if spending on coffee purchases varies among age groups. 

- Provide constructive feedback on any issues with file and/or code organization.

We recommend suppressing some of the terminal output such as warning and messages to make the file more concise. 

Consider additional analyses for subgroups such as gender or location to add more depth to analyze. 

- (Optional) Any further comments or feedback?

**Comment by lestrada** [comment]
Thank you for the feedback. Added additional variables to Q2 in order to quantify the favorite kind of coffee across categorical variables. Plot inspiration was the duBois plots from HW3. 
Also suppressed warnings and messages.
