### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by dwiesneraz** [INFO-526-SU24/final-project-lestrada#2]
The following is the peer review of the project proposal by Daniel Wiesner. The team members that participated in this review are 

- Daniel Wiesner @dwiesneraz 

- Describe the goal of the project.

The goal is to gain insight into the tastes and spending habits of coffee drinkers, focusing on age groups.

- Describe the data used or collected.

The dataset was collected through a coffee taste test Youtube event. While the event was primarily put together to taste test four different types of coffee, a great deal of descriptive information was collected throughout. It contains information both about the people drinking and many fields for descriptive information about the coffee.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

Both Questions:
     Create new aggregate variables for total spent and favorite drinks for each age group. Display aggregates using heat maps or stacked bar charts.
     

- Is there anything that is unclear from the proposal?

The goals are clear but I think that a little more detail would be helpful in explaining your process and/or describing the plots you are considering.

- Provide constructive feedback on how the team might be able to improve their project.

As far as I can tell, you are working solo. If that is the case then I would recommend reviewing Dr. Chism's Slack post explaining that those working solo only need 1 question and 2 plots for that question. If you are still planning on doing 2 questions, I would recommend reaching out to Dr. Chism about it. Regardless, your plot descriptions could be clearer about which plot you are thinking of using for each of your questions. Since you are working with 2 categorical variables I think both a heatmap and stacked bar chart would be a good idea, and since you need 2 plots per question, I think it would be a good idea to do both.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

I'm most interested to see how favorite drinks vary throughout the age groups. New coffee drinks and experiments have become very popular in the last few years, especially on social media, and I'm interested to see how they have influenced the different generations.

- Provide constructive feedback on any issues with file and/or code organization.

Overall organization is quite good. You may consider adding a 'Setup' header above the package install/load section or adding a more distinct label for the task list but neither of these are big issues. I think it would also be helpful for you to add short summaries in your task list to explain your process a little better.

- (Optional) Any further comments or feedback?

**Comment by lestrada** [comment]
Thank you for the feedback. I was not aware of the working solo 1 question 2 plots requirement. I will follow up with Dr. Chism per your suggestion. I think either question could expand upon to make multiple plots. 
Tried to add more details to each question for more clarity. 
Also started to add summaries to the task list
